<a href="https://colab.research.google.com/github/maddoxplecko/PyTorch-Projects/blob/main/MathTensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a

tensor([1, 2, 3, 4])

In [7]:
# Addition
tensor_a + tensor_b
# Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
# Subtraction
tensor_a - tensor_b
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multiplication
tensor_a * tensor_b
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
# Division
tensor_b / tensor_a
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder Modulos
tensor_b % tensor_a
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents
tensor_a ** tensor_b
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
# Reassignment
tensor_a + tensor_b
tensor_a.add_(tensor_b) # the underscore will update tensor_a with the result
tensor_a

tensor([11, 14, 17, 20])