<a href="https://colab.research.google.com/github/maddoxplecko/PyTorch-Projects/blob/main/ReshapingAndSlicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshaping to manipulate data
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
# Reshaping when data is unknown using -1
my_torch2 = torch.arange(10)
my_torch2



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
# Using view accomplishes the same thing
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Reshaping and Viewing will update
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
my_torch5[1] = 4141
my_torch5
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [13]:
# Slicing
my_torch7 = torch.arange(10)
my_torch7[7] # This will give an item
my_torch8 = my_torch7.reshape(5,2)
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])