<a href="https://colab.research.google.com/github/maddoxplecko/PyTorch-Projects/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.66550469, 0.31237544, 0.24057309, 0.50256213],
       [0.41290796, 0.80842862, 0.27431163, 0.11436232],
       [0.17532163, 0.98961483, 0.39020383, 0.77459019]])

In [4]:
np1.dtype

dtype('float64')

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d
## tensor_2d.dtype

tensor([[ 1.4616, -0.7325,  0.5295,  0.1343],
        [ 0.1804,  0.5901, -0.2211, -1.4714],
        [ 0.6256, -0.5721,  0.2261,  0.6500]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6655, 0.3124, 0.2406, 0.5026],
        [0.4129, 0.8084, 0.2743, 0.1144],
        [0.1753, 0.9896, 0.3902, 0.7746]], dtype=torch.float64)

In [ ]:
## Tensor Documentation: google -> pytorch tensor